using Microsoft.EntityFrameworkCore;
using JS = Microsoft.JSInterop.IJSRuntime;

namespace HiokiNL2SQLMark1.Logic;
/// <summary>
/// Model class for a FCT table. Inherits from LogTableLogic
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread</param>
/// <param name="js">To handle saving to CSV</param>
/// <param name="navService">To navigate away for barcode "drill-down"</param>
public class FctTableLogic(IDbContextFactory<LogDbContext> dbFactory, JS js, INavService navService) :
    LogTableLogic<FctResult>(dbFactory, db => db.FctView, js, navService)
{
    public override string TableName => "fct"; // This table's internal "type" as it would appear in currentType
    public override string DisplayName => "FCT Results"; // The label to apply to this table in the view

    /// <summary>
    /// Populates FCT-specific filters in parent's filter registry
    /// </summary>
    protected override void InitializeFilters()
    {
        base.InitializeFilters();

        Filters["step"] = new Filter<int?>("step", null) { OnChanged = NotifyStateChanged };
        Filters["mode"] = new Filter<string?>("mode", null) { OnChanged = NotifyStateChanged };
    }

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the FCT-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core
    /// </summary>
    /// <param name="query">The query to which the filters will be applied</param>
    /// <returns>The query, with all filters applied</returns>
    public override IQueryable<FctResult> ApplyFilters(IQueryable<FctResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        var filterStep = GetFilter<int?>("step");
        var filterMode = GetFilter<string?>("mode");

        // Apply FCT-specific filters
        if (filterStep.IsActive)
            query = filterStep.IsNegated
                ? query = query.Where(s => s.Step != filterStep.Value)
                : query = query.Where(s => s.Step == filterStep.Value);

        if (filterMode.IsActive)
            query = filterMode.IsNegated
                ? query.Where(s => !s.Mode.Contains(filterMode.Value))
                : query.Where(s => s.Mode.Contains(filterMode.Value));

        return query;
    }
}