using Microsoft.EntityFrameworkCore;
using JS = Microsoft.JSInterop.IJSRuntime;
using NavigationManager = Microsoft.AspNetCore.Components.NavigationManager;

namespace HiokiNL2SQLMark1.Logic;
/// <summary>
/// Model class for a group table. Inherits from LogTableLogic
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread</param>
/// <param name="js">To handle saving to CSV</param>
/// <param name="navManager">To navigate away for barcode "drill-down"</param>
public class GroupTableLogic(IDbContextFactory<LogDbContext> dbFactory, JS js, NavigationManager navManager) : 
    LogTableLogic<GroupResult>(dbFactory, db => db.GroupView, js, navManager)
{
    public override string TableName => "group"; // This table's internal "type" as it would appear in currentType
    public override string DisplayName => "Group Results"; // The label to apply to this table in the view

    /// <summary>
    /// Populates group-specific filters in parent's filter registry
    /// </summary>
    protected override void InitializeFilters()
    {
        base.InitializeFilters();

        Filters["comp"] = new Filter<string?>("comp", null) { OnChanged = NotifyStateChanged };
        Filters["short"] = new Filter<string?>("short", null) { OnChanged = NotifyStateChanged };
        Filters["macro"] = new Filter<string?>("macro", null) { OnChanged = NotifyStateChanged };
        Filters["ic"] = new Filter<string?>("ic", null) { OnChanged = NotifyStateChanged };
        Filters["function"] = new Filter<string?>("function", null) { OnChanged = NotifyStateChanged };
    }

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the group-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core
    /// </summary>
    /// <param name="query">The query to which the filters will be applied</param>
    /// <returns>The query, with all filters applied</returns>
    public override IQueryable<GroupResult> ApplyFilters(IQueryable<GroupResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        var filterComp = GetFilter<string?>("comp");
        var filterShort = GetFilter<string?>("short");
        var filterMacro = GetFilter<string?>("macro");
        var filterIC = GetFilter<string?>("ic");
        var filterFunction = GetFilter<string?>("function");

        // Apply Group-specific filters
        if (filterComp.IsActive)
            query = filterComp.IsNegated
                ? query.Where(g => !g.ComponentTest.Contains(filterComp.Value))
                : query.Where(g => g.ComponentTest.Contains(filterComp.Value));

        if (filterShort.IsActive)
            query = filterShort.IsNegated
                ? query.Where(g => !g.ShortTest.Contains(filterShort.Value))
                : query.Where(g => g.ShortTest.Contains(filterShort.Value));

        if (filterMacro.IsActive)
            query = filterMacro.IsNegated
                ? query.Where(g => !g.MacroTest.Contains(filterMacro.Value))
                : query.Where(g => g.MacroTest.Contains(filterMacro.Value));

        if (filterIC.IsActive)
            query = filterIC.IsNegated
                ? query.Where(g => !g.IcTest.Contains(filterIC.Value))
                : query.Where(g => g.IcTest.Contains(filterIC.Value));

        if (filterFunction.IsActive)
            query = filterFunction.IsNegated
                ? query.Where(g => !g.FunctionTest.Contains(filterFunction.Value))
                : query.Where(g => g.FunctionTest.Contains(filterFunction.Value));

        return query;
    }
}