using Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage;
using Microsoft.EntityFrameworkCore;

namespace HiokiNL2SQLMark1.Logic;
/// <summary>
/// Model class for a group table. Inherits from LogTableLogic
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread</param>
/// <param name="js">To handle saving to CSV</param>
/// <param name="navService">To navigate away for barcode "drill-down"</param>
public class GroupTableLogic(IDbContextFactory<LogDbContext> dbFactory, IJSService js, INavService navService) : 
    LogTableLogic<GroupResult>(dbFactory, db => db.GroupView, js, navService)
{
    public override string TableName => "group"; // This table's internal "type" as it would appear in currentType
    public override string DisplayName => "Group Results"; // The label to apply to this table in the view
    public List<string> CompCache { get; set; } = []; // The list of component test results to choose from
    public List<string> ShortCache { get; set; } = []; // The list of short-circuit test results to choose from
    public List<string> OpenCache { get; set; } = []; // The list of open-circuit test results to choose from
    public List<string> MacroCache { get; set; } = []; // The list of macro test results to choose from
    public List<string> IcCache { get; set; } = []; // The list of IC test results to choose from
    public List<string> FunctionCache { get; set; } = []; // The list of functional test results to choose from

    /// <summary>
    /// Populates group-specific filters in parent's filter registry
    /// </summary>
    protected override void InitializeFilters()
    {
        base.InitializeFilters();

        Filters["comp"] = new Filter<string?>("comp", null) { OnChanged = NotifyStateChanged };
        Filters["short"] = new Filter<string?>("short", null) { OnChanged = NotifyStateChanged };
        Filters["open"] = new Filter<string?>("open", null) { OnChanged = NotifyStateChanged };
        Filters["macro"] = new Filter<string?>("macro", null) { OnChanged = NotifyStateChanged };
        Filters["ic"] = new Filter<string?>("ic", null) { OnChanged = NotifyStateChanged };
        Filters["function"] = new Filter<string?>("function", null) { OnChanged = NotifyStateChanged };
    }

    /// <summary>
    /// Initialize the caches that hold group sub-test result types
    /// </summary>
    /// <returns></returns>
    public override async Task InitializeCaches()
    {
        // Run parent's initializer for the result type cache
        var baseTask = base.InitializeCaches();

        var compTask = GetDistinctList("ComponentTest");
        var shortTask = GetDistinctList("ShortTest");
        var openTask = GetDistinctList("OpenTest");
        var macroTask = GetDistinctList("MacroTest");
        var icTask = GetDistinctList("IcTest");
        var functionTask = GetDistinctList("FunctionTest");

        // Wait for everything to finish at once
        await Task.WhenAll(baseTask, compTask, shortTask, openTask, macroTask, icTask, functionTask);

        // Assign the results
        CompCache = await compTask;
        ShortCache = await shortTask;
        OpenCache = await openTask;
        MacroCache = await macroTask;
        IcCache = await icTask;
        FunctionCache = await functionTask;
    }

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the group-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core
    /// </summary>
    /// <param name="query">The query to which the filters will be applied</param>
    /// <returns>The query, with all filters applied</returns>
    public override IQueryable<GroupResult> ApplyFilters(IQueryable<GroupResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        var filterComp = GetFilter<string?>("comp");
        var filterShort = GetFilter<string?>("short");
        var filterOpen = GetFilter<string?>("open");
        var filterMacro = GetFilter<string?>("macro");
        var filterIC = GetFilter<string?>("ic");
        var filterFunction = GetFilter<string?>("function");

        // Apply Group-specific filters
        if (filterComp.IsActive)
            query = filterComp.IsNegated
                ? query.Where(g => !g.ComponentTest.Contains(filterComp.Value))
                : query.Where(g => g.ComponentTest.Contains(filterComp.Value));

        if (filterShort.IsActive)
            query = filterShort.IsNegated
                ? query.Where(g => !g.ShortTest.Contains(filterShort.Value))
                : query.Where(g => g.ShortTest.Contains(filterShort.Value));

        if (filterOpen.IsActive)
            query = filterOpen.IsNegated
                ? query.Where(g => !g.OpenTest.Contains(filterOpen.Value))
                : query.Where(g => g.OpenTest.Contains(filterOpen.Value));

        if (filterMacro.IsActive)
            query = filterMacro.IsNegated
                ? query.Where(g => !g.MacroTest.Contains(filterMacro.Value))
                : query.Where(g => g.MacroTest.Contains(filterMacro.Value));

        if (filterIC.IsActive)
            query = filterIC.IsNegated
                ? query.Where(g => !g.IcTest.Contains(filterIC.Value))
                : query.Where(g => g.IcTest.Contains(filterIC.Value));

        if (filterFunction.IsActive)
            query = filterFunction.IsNegated
                ? query.Where(g => !g.FunctionTest.Contains(filterFunction.Value))
                : query.Where(g => g.FunctionTest.Contains(filterFunction.Value));

        return query;
    }
}