using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;
using JS = Microsoft.JSInterop.IJSRuntime;
using NavigationManager = Microsoft.AspNetCore.Components.NavigationManager;

namespace HiokiNL2SQLMark1.Logic;
/// <summary>
/// Model class for a step table. Inherits from LogTableLogic
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread</param>
/// <param name="js">To handle saving to CSV</param>
/// <param name="navManager">To navigate away for barcode "drill-down"</param>
public class StepTableLogic(IDbContextFactory<LogDbContext> dbFactory, JS js, NavigationManager navManager) :
    LogTableLogic<StepResult>(dbFactory, db => db.StepView, js, navManager)
{
    public override string TableName => "step"; // This table's internal "type" as it would appear in currentType
    public override string DisplayName => "Step Results"; // The label to apply to this table in the view

    /// <summary>
    /// Populates step-specific filters in parent's filter registry
    /// </summary>
    protected override void InitializeFilters()
    {
        base.InitializeFilters();

        Filters["part"] = new Filter<string?>("part", null) { OnChanged = NotifyStateChanged };
        Filters["step"] = new Filter<int?>("step", null) { OnChanged = NotifyStateChanged };
        Filters["mode"] = new Filter<string?>("mode", null) { OnChanged = NotifyStateChanged };
    }

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the step-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core
    /// </summary>
    /// <param name="query">The query to which the filters will be applied</param>
    /// <returns>The query, with all filters applied</returns>
    public override IQueryable<StepResult> ApplyFilters(IQueryable<StepResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        var filterStep = GetFilter<int?>("step");
        var filterPartName = GetFilter<string>("part");
        var filterMode = GetFilter<string?>("mode");

        // Apply Step-specific filters
        if (filterStep.IsActive)
            query = filterStep.IsNegated
                ? query = query.Where(s => s.Step != filterStep.Value)
                : query = query.Where(s => s.Step == filterStep.Value);

        if (filterPartName.IsActive)
            query = filterPartName.IsNegated
                ? query.Where(s => !s.PartName.Contains(filterPartName.Value))
                : query.Where(s => s.PartName.Contains(filterPartName.Value));

        if (filterMode.IsActive)
            query = filterMode.IsNegated
                ? query.Where(s => !s.Mode.Contains(filterMode.Value))
                : query.Where(s => s.Mode.Contains(filterMode.Value));

        return query;
    }
}