// <copyright file="FctTableLogic.cs" company="Stanley Electric US Co. Inc.">
// Copyright (c) 2026 Stanley Electric US Co. Inc. Licensed under the MIT License.
// </copyright>

namespace HiokiNL2SQL.Logic;

using Microsoft.EntityFrameworkCore;

/// <summary>
/// Model class for a FCT table. Inherits from LogTableLogic.
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread.</param>
/// <param name="js">To handle saving to CSV.</param>
/// <param name="navService">To navigate away for barcode "drill-down".</param>
public class FctTableLogic(IDbContextFactory<LogDbContext> dbFactory, IJSService js, INavService navService) :
    LogTableLogic<FctResult>(dbFactory, db => db.FctView, js, navService)
{
    /// <summary>
    /// Gets this table's internal "type" as it would appear in <see cref="PowerSearchLogic.CurrentType"/>.
    /// </summary>
    public override string TableName => "fct";

    /// <summary>
    /// Gets the label to apply to this table in the view.
    /// </summary>
    public override string DisplayName => "FCT Results";

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the FCT-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core.
    /// </summary>
    /// <param name="query">The query to which the filters will be applied.</param>
    /// <returns>The query, with all filters applied.</returns>
    public override IQueryable<FctResult> ApplyFilters(IQueryable<FctResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        Filter<int?> filterStep = this.GetFilter<int?>("step");
        Filter<string?> filterMode = this.GetFilter<string?>("mode");

        // Apply FCT-specific filters
        return query
            .ApplyFilterIfActive(
                filterStep,
                f => f.Step != filterStep.Value,
                f => f.Step == filterStep.Value)
            .ApplyFilterIfActive(
                filterMode,
                f => f.Mode != null && !f.Mode.Contains(filterMode.Value!),
                f => f.Mode != null && f.Mode.Contains(filterMode.Value!));
    }

    /// <summary>
    /// Populates FCT-specific filters in parent's filter registry.
    /// </summary>
    protected override void InitializeFilters()
    {
        base.InitializeFilters();

        this.Filters["step"] = new Filter<int?>("step", null) { OnChanged = this.NotifyStateChanged };
        this.Filters["mode"] = new Filter<string?>("mode", null) { OnChanged = this.NotifyStateChanged };
    }
}
