// <copyright file="GroupTableLogic.cs" company="Stanley Electric US Co. Inc.">
// Copyright (c) 2026 Stanley Electric US Co. Inc. Licensed under the MIT License.
// </copyright>

namespace HiokiNL2SQL.Logic;

using Microsoft.EntityFrameworkCore;
using System.Linq.Expressions;

/// <summary>
/// Model class for a group table. Inherits from LogTableLogic.
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread.</param>
/// <param name="js">To handle saving to CSV.</param>
/// <param name="navService">To navigate away for barcode "drill-down".</param>
public class GroupTableLogic(IDbContextFactory<LogDbContext> dbFactory, IJSService js, INavService navService) :
    LogTableLogic<GroupResult>(dbFactory, db => db.GroupView, js, navService, CreateFilters())
{
    /// <summary>
    /// Gets this table's internal "type" as it would appear in <see cref="PowerSearchLogic.CurrentType"/>.
    /// </summary>
    public override string TableName => "group";

    /// <summary>
    /// Gets the label to apply to this table in the view.
    /// </summary>
    public override string DisplayName => "Group Results";

    /// <summary>
    /// Gets or sets the list of component test results to choose from.
    /// </summary>
    public HashSet<string> CompCache { get; set; } = [];

    /// <summary>
    /// Gets or sets the list of short-circuit test results to choose from.
    /// </summary>
    public HashSet<string> ShortCache { get; set; } = [];

    /// <summary>
    /// Gets or sets the list of open-ciruit test results to choose from.
    /// </summary>
    public HashSet<string> OpenCache { get; set; } = [];

    /// <summary>
    /// Gets or sets the list of macro test results to choose from.
    /// </summary>
    public HashSet<string> MacroCache { get; set; } = [];

    /// <summary>
    /// Gets or sets the list of IC test results to choose from.
    /// </summary>
    public HashSet<string> IcCache { get; set; } = [];

    /// <summary>
    /// Gets or sets the list of functional test results to choose from.
    /// </summary>
    public HashSet<string> FunctionCache { get; set; } = [];

    /// <summary>
    /// Initialize the caches that hold group sub-test result types.
    /// </summary>
    /// <returns>A Task representing that the caches have been initialized.</returns>
    public override async Task InitializeCaches()
    {
        // Hydration check
        if (this.LastQueryHash != null && this.CompCache.Count != 0)
        {
            return;
        }

        // Run parent's initializer for the result type cache
        Task baseTask = base.InitializeCaches();

        Task<HashSet<string>> compTask = this.GetCacheSet("ComponentTest");
        Task<HashSet<string>> shortTask = this.GetCacheSet("ShortTest");
        Task<HashSet<string>> openTask = this.GetCacheSet("OpenTest");
        Task<HashSet<string>> macroTask = this.GetCacheSet("MacroTest");
        Task<HashSet<string>> icTask = this.GetCacheSet("IcTest");
        Task<HashSet<string>> functionTask = this.GetCacheSet("FunctionTest");

        // Wait for everything to finish at once
        await Task.WhenAll(baseTask, compTask, shortTask, openTask, macroTask, icTask, functionTask);

        // Assign the results
        this.CompCache = await compTask;
        this.ShortCache = await shortTask;
        this.OpenCache = await openTask;
        this.MacroCache = await macroTask;
        this.IcCache = await icTask;
        this.FunctionCache = await functionTask;
    }

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the group-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core.
    /// </summary>
    /// <param name="query">The query to which the filters will be applied.</param>
    /// <returns>The query, with all filters applied.</returns>
    public override IQueryable<GroupResult> ApplyFilters(IQueryable<GroupResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        Filter<string?> filterComp = this.GetFilter<string?>("comp");
        Filter<string?> filterShort = this.GetFilter<string?>("short");
        Filter<string?> filterOpen = this.GetFilter<string?>("open");
        Filter<string?> filterMacro = this.GetFilter<string?>("macro");
        Filter<string?> filterIC = this.GetFilter<string?>("ic");
        Filter<string?> filterFunction = this.GetFilter<string?>("function");

        return query
            .ApplyFilterIfActive(
                filterComp,
                g => g.ComponentTest != null && !g.ComponentTest.Contains(filterComp.Value!),
                g => g.ComponentTest != null && g.ComponentTest.Contains(filterComp.Value!))
            .ApplyFilterIfActive(
                filterShort,
                g => g.ShortTest != null && !g.ShortTest.Contains(filterShort.Value!),
                g => g.ShortTest != null && g.ShortTest.Contains(filterShort.Value!))
            .ApplyFilterIfActive(
                filterOpen,
                g => g.OpenTest != null && !g.OpenTest.Contains(filterOpen.Value!),
                g => g.OpenTest != null && g.OpenTest.Contains(filterOpen.Value!))
            .ApplyFilterIfActive(
                filterMacro,
                g => g.MacroTest != null && !g.MacroTest.Contains(filterMacro.Value!),
                g => g.MacroTest != null && g.MacroTest.Contains(filterMacro.Value!))
            .ApplyFilterIfActive(
                filterIC,
                g => g.IcTest != null && !g.IcTest.Contains(filterIC.Value!),
                g => g.IcTest != null && g.IcTest.Contains(filterIC.Value!))
            .ApplyFilterIfActive(
                filterFunction,
                g => g.FunctionTest != null && !g.FunctionTest.Contains(filterFunction.Value!),
                g => g.FunctionTest != null && g.FunctionTest.Contains(filterFunction.Value!));
    }

    /// <summary>
    /// Creates group-specific filters for the parent to add to the registry.
    /// </summary>
    private static IEnumerable<IFilter> CreateFilters() =>
    [
        new Filter<string?>("comp", null),
        new Filter<string?>("short", null),
        new Filter<string?>("open", null),
        new Filter<string?>("macro", null),
        new Filter<string?>("ic", null),
        new Filter<string?>("function", null),
    ];
}
