// <copyright file="StepTableLogic.cs" company="Stanley Electric US Co. Inc.">
// Copyright (c) 2026 Stanley Electric US Co. Inc. Licensed under the MIT License.
// </copyright>

namespace HiokiNL2SQL.Logic;

using Microsoft.EntityFrameworkCore;

/// <summary>
/// Model class for a step table. Inherits from LogTableLogic.
/// </summary>
/// <param name="dbFactory">Generates a new DB context per thread.</param>
/// <param name="js">To handle saving to CSV.</param>
/// <param name="navService">To navigate away for barcode "drill-down".</param>
public class StepTableLogic(IDbContextFactory<LogDbContext> dbFactory, IJSService js, INavService navService) :
    LogTableLogic<StepResult>(dbFactory, db => db.StepView, js, navService, CreateFilters())
{
    /// <summary>
    /// Gets this table's internal "type" as it would appear in <see cref="PowerSearchLogic.CurrentType"/>.
    /// </summary>
    public override string TableName => "step";

    /// <summary>
    /// Gets the label to apply to this table in the view.
    /// </summary>
    public override string DisplayName => "Step Results";

    /// <summary>
    /// Calls the base class to apply the generic filters, then applies the step-specific ones
    /// Used to draft the WHERE clauses for the SQL query generated by EF Core.
    /// </summary>
    /// <param name="query">The query to which the filters will be applied.</param>
    /// <returns>The query, with all filters applied.</returns>
    public override IQueryable<StepResult> ApplyFilters(IQueryable<StepResult> query)
    {
        // Apply the base filters (Barcode, Date, etc.)
        query = base.ApplyFilters(query);

        Filter<int?> filterStep = this.GetFilter<int?>("step");
        Filter<string?> filterPartName = this.GetFilter<string?>("part");
        Filter<string?> filterMode = this.GetFilter<string?>("mode");

        return query
            .ApplyFilterIfActive(
                filterStep,
                s => s.Step != filterStep.Value,
                s => s.Step == filterStep.Value)
            .ApplyFilterIfActive(
                filterPartName,
                s => s.PartName != null && !s.PartName.Contains(filterPartName.Value!),
                s => s.PartName != null && s.PartName.Contains(filterPartName.Value!))
            .ApplyFilterIfActive(
                filterMode,
                s => s.Mode != null && !s.Mode.Contains(filterMode.Value!),
                s => s.Mode != null && s.Mode.Contains(filterMode.Value!));
    }

    /// <summary>
    /// Creates step-specific filters for the parent to add to the registry.
    /// </summary>
    private static IEnumerable<IFilter> CreateFilters() =>
    [
        new Filter<string?>("part", null),
        new Filter<int?>("step", null),
        new Filter<string?>("mode", null),
    ];
}
