<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!-- Only generates the XML doc when in debug mode -->
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor.Bootstrap" Version="3.5.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.*" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
  </ItemGroup>

  <!-- Only use StyleCop when in debug mode -->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <!-- Setting private assets ensures this dependency is ignored in production -->
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <AdditionalFiles Include="../stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterProcessIO\InterProcessIO.csproj" />
    <ProjectReference Include="..\HiokiParserMark1\HiokiParserMark1.csproj" />
  </ItemGroup>

</Project>
